add -DADAFRUIT_ARCH_SAMD to all board's build.extra_flags
adafruit/ArduinoCore-samd pull request #306
Opened 2021-07-15 01:48 UTC by 2bndy5

resolves #305 

I chose the macro ADAFRUIT_ARCH_SAMD as it seems most like using ARDUINO_ARCH_SAMD macro.

tested with 
```cpp
            #if defined (ADAFRUIT_ARCH_SAMD)
                // using the adafruit/ArduinoCore-samd repo
                #define printf_P Serial.printf
            #endif // defined (ADAFRUIT_ARCH_SAMD)

2021-07-15 02:07 UTC, 2bndy5 commented
to be able to use this macro in PlatformIO, I'm guessing I would have to submit a similar PR to  platformio/platform-atmelsam repo right?

2021-07-15 06:23 UTC, hathach requested changes
`ARDUINO` in ARCH macro is meant for arduino platform not the core repo. Please use `ARDUINO_SAMD_ADAFRUIT` as suggested previously. The macro should be added next to the arch one `-DARDUINO_ARCH_{build.arch}` in the platform.txt instead of boards.txt. There are 3 of them.

https://github.com/adafruit/ArduinoCore-samd/blob/master/platform.txt#L94

2021-07-15 07:24 UTC, 2bndy5 commented
@hathach Thanks for the guidance. I was really kinda poking in the dark here (not sure if the Arduino wiki has this info somewhere).

2021-07-15 15:24 UTC, hathach approved these changes
Thanks for your pr. Look great

2021-07-15 17:19 UTC, merged

2021-07-17 21:24 UTC, ladyada commented
thanks @2bndy5 and good work!